# -*- coding: utf-8 -*-
"""Manojoshigeorge_Final_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tKiYtiOzEv6BKP9w10BBv1YGpPXOve1O

PROJECT TITLE

#Salary Trends in Data field Careers

DOMAIN

Human Resource Analytics(Business)

OBJECTIVE

To analyze global salary trends in data-related jobs and identify the key factors that influence salary variation across roles, experience levels, company size, and locations. Additionally, to build a predictive model that can estimate salary based on job and company attributes.

OUTCOME

This analysis clearly shows how salary varies by role, experience, country, company size, and remote work. These insights help HR make better salary decisions, and the predictive model gives an approximate salary estimate for new job profiles.

DATASET INFORMATION

SOURCE: Kaggle

YEAR: This dataset contains salary information recorded for the year 2024

DATASET DESCRIPTION: A salary dataset for various data roles with details like job title, experience, country, company size, remote ratio, and salary in USD

NAME: Jobs and Salaries in Data Field – 2024

TYPE OF ANALYSIS

Predictive Analysis

#STAGE 1
# DATA STATEMENT

Problem Definiton :
                   
   Companies face difficulty deciding the correct salary for data-related roles because pay changes a lot based on job title, experience, company size, and location. This creates challenges in offering competitive packages during hiring. So the business problem is to understand global salary trends and identify the factors that influence salary differences.

Expected Outcome:
                
 The analysis will show which factors affect salary the most and how pay varies across roles and countries. This helps HR make better hiring and salary decisions. The predictive model also gives an estimated salary for new job profiles.

Dataset Name:
   Jobs and Salaries in Data Field – 2024

Source: Collected from Kaggle.

Size: It contains salary records across different countries for the year 2024.
(Usually around 10k+ rows depending on the version)

Features: work_year – salary year

experience_level – EN, MI, SE, EX

employment_type – FT, PT, CT

job_title

salary

salary_currency

salary_in_usd

employee_residence

remote_ratio

company_location

company_size – S, M, L

#Load the Data set
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

"""Dataset Description &  initial EDA

"""

import pandas as pd
df = pd.read_csv("jobs_in_data_2024.csv")
df.head()

df.describe(include="all")

df.head()

df.info()

df.shape

df.isnull().sum()

df.duplicated().sum()



"""#STAGE 2

Data cleaning and Pre-processing
"""

df =df.dropna() #Missing values

df = df.drop_duplicates() #Remove duplicates

df.columns = df.columns.str.lower().str.replace(" ", "_").str.strip() #Clean Column Names

df['salary_in_usd'] = pd.to_numeric(df['salary_in_usd'], errors='coerce') #Convert salary into numeric

columns = ['job_title','experience_level','employment_type','company_size', #Convert Important columns to category
        'employee_residence','company_location']

for c in columns:
    if c in df.columns:
        df[c] = df[c].astype('category')

#Standardize categorical columns & values
if "experience_level" in df.columns:
    df["experience_level"] = df["experience_level"].replace({
        "EN": "Entry-level",
        "MI": "Mid-level",
        "SE": "Senior-level",
        "EX": "Executive-level"
    })

# Similarly, for employment_type or remote_ratio or company_size (if applicable)
if "employment_type" in df.columns:
    df["employment_type"] = df["employment_type"].replace({
        "FT": "Full-time",
        "PT": "Part-time",
        "CT": "Contract",
        "FL": "Freelance"
    })

if "remote_ratio" in df.columns:
    df["remote_ratio"] = df["remote_ratio"].replace({
        0: "Onsite",
        50: "Hybrid",
        100: "Remote"
    })

    # Assuming 'On-site' might be present if 0 was replaced by this previously
elif "work_setting" in df.columns:
    df["work_setting"] = df["work_setting"].replace({
        "On-site": "Onsite",
        "Hybrid": "Hybrid",
        "Remote": "Remote"
    })

if "company_size" in df.columns:
    df["company_size"] = df["company_size"].replace({
        "S": "Small",
        "M": "Medium",
        "L": "Large"
    })

#Remove Salary Outliers
Q1= df['salary_in_usd'].quantile(0.25)
Q3 = df['salary_in_usd'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df = df[(df['salary_in_usd'] >= lower) & (df['salary_in_usd'] <= upper)]

#Convert Data Types
df['work_year'] = df['work_year'].astype(int)
df['salary_in_usd'] = df['salary_in_usd'].astype(float)

#Salary range
def salary_range(s):
    if s < 50000:
        return "Low"
    elif s < 120000:
        return "Medium"
    else:
        return "High"

df['salary_range'] = df['salary_in_usd'].apply(salary_range)

#Annual package
INR_RATE = 83  # approx USD → INR
df['annual_lpa'] = (df['salary_in_usd'] * INR_RATE) / 100000

#Experince level numeric
exp_map = {
    "Entry-level": 1,
    "Mid-level": 2,
    "Senior-level": 3,
    "Executive": 4
}

df['experience_level_num'] = df['experience_level'].map(exp_map)

#Company Size Category → Numeric
size_map = {"S": 1, "M": 2, "L": 3}
df['company_size_num'] = df['company_size'].map(size_map)

#Salary per Month Column
df['monthly_salary_usd'] = df['salary_in_usd'] / 12

def job_type(title): #JOB analyse
    title = title.lower()
    if 'engineer' in title:
        return 'Engineer'
    elif 'scientist' in title:
        return 'Scientist'
    elif 'analyst' in title:
        return 'Analyst'
    elif 'manager' in title:
        return 'Manager'
    else:
        return 'Other'

df['job_type'] = df['job_title'].apply(job_type)

def seniority(level): #Seniority level analyse
    if level in ['Entry-level']:
        return "Junior"
    elif level in ['Mid-level']:
        return "Mid"
    else:
        return "Senior"

df['seniority'] = df['experience_level'].apply(seniority)

df['hourly_salary_usd'] = df['salary_in_usd'] / 2080 # Salary normalize

del df['experience_level_num']

del df['company_size_num']

df.isnull().sum()

df.info()

print("Data cleaning completed succesfully..!")

df.head()

"""#EDA & DATA VIUALIZATION"""

df.nunique()

df.describe()

df.isnull().sum()

"""#UNIVARIVATE ANALYSIS

#Count plot
"""

plt.figure(figsize=(12, 20))

job_counts = df['job_title'].value_counts()

sns.barplot(
    y=job_counts.index,
    x=job_counts.values
)

plt.xlabel("Count of Job Titles")
plt.ylabel("Job Title")
plt.title("Job Title Distribution")
plt.tight_layout()
plt.show()

"""1 CHART : COUNT PLOT (Job title distrubition)

Chart Explanation: Shows which job titles appear most.

What it’s saying: Some jobs are very common, some rare.

Features used: job_title

Showing : Job title frequency.

#Histogram
"""

plt.figure(figsize=(10,5))
sns.histplot(df['salary_in_usd'], kde=True, bins=40)
plt.title("Salary Distribution")
plt.xlabel("Salary (USD)")
plt.show()

"""2 CHART: HISTOGRAM (Salary distrubition)

Chart Explanation: Shows how salaries are spread.

What it’s saying: Which salary ranges are common or high/low.

Features used: salary_in_usd

Showing us: Overall salary pattern.

# Boxplot
"""

plt.figure(figsize=(8,6))
sns.boxplot(x=df['experience_level'], y=df['salary_in_usd'])
plt.title("Salary vs Experience")
plt.show()

"""3 CHART: BOX PLOT (Salary vs Experience)

Chart Explanation: Shows salary range for each experience level.

What it’s saying: Higher experience → higher salary.

Features used: experience_level, salary_in_usd

Showing us: Salary differences by experience.

#BIVARIATE ANALYSIS

#Scatter plot
"""

plt.figure(figsize=(9,6))
sns.scatterplot(
    data=df,
    x='work_setting',
    y='salary_in_usd',
    hue='experience_level',
    alpha=0.6,
    s=40
)

plt.title("Scatter Plot: Salary vs Work Setting by Experience Level")
plt.xlabel("Work Setting")
plt.ylabel("Salary (USD)")
plt.legend(title="Experience Level")
plt.show()

"""4 CHART: SCATTER PLOT (Work Setting vs Salary)

Chart Explanation: Salary changes across remote/hybrid/office.

What it’s saying: Work setting and experience influence salary.

Features used: work_setting, salary_in_usd, experience_level

Showing us: Salary variation based on work style + experience.

#Bar plot
"""

exp_salary = df.groupby('experience_level')['salary_in_usd'].mean().reset_index()

plt.figure(figsize=(8,5))
sns.barplot(data=exp_salary, x='experience_level', y='salary_in_usd', palette='crest')

plt.title("Average Salary by Experience Level")
plt.xlabel("Experience Level")
plt.ylabel("Average Salary (USD)")
plt.show()

"""5 CHART: BAR PLOT (Avg Salary by Experience)

Chart Explanation: Shows mean salary for each experience level.


What it’s saying: Experienced people earn more on average.

Features used: experience_level, salary_in_usd

Showing us: Salary trend by experience.

#Correlation Heat map
"""

numeric_df = df.select_dtypes(include=['number'])
plt.figure(figsize=(7,5))
sns.heatmap(numeric_df.corr(), annot=True, cmap="Blues")
plt.title("Correlation Heatmap")
plt.show()

"""6 CHART: CORRELATION HEATMAP

Explain the chart: Shows correlations between numeric variables.

What it’s saying: Which features relate strongly to salary.

Features used: Numeric columns like salary_in_usd.

Showing us: Strength of relationships among numeric data.

# MULTIVARIATE ANALYSIS

#Pair plot
"""

pair_cols = [col for col in ['salary_in_usd','remote_ratio'] if col in df.columns]

if 'company_size' in df.columns:
    df['company_size_code'] = df['company_size'].astype('category').cat.codes
    pair_cols.append('company_size_code')

if len(pair_cols)>=2:
    sns.pairplot(df[pair_cols].dropna(), diag_kind='kde')

"""7 CHART: PAIR PLOT

Chart Explanation: Shows interaction between multiple numeric features.

What it’s saying: How salary, remote ratio, company size connect.

Features used: salary_in_usd, remote_ratio, company_size_code

Showing us: Multi-feature patterns or clusters.

#Grouped analysis
"""

grouped_exp_country = df.groupby(['experience_level','employee_residence'])['salary_in_usd'].mean().reset_index()

plt.figure(figsize=(12,6))
sns.barplot(data=grouped_exp_country, x='experience_level', y='salary_in_usd', hue='employee_residence')
plt.title("Average Salary by Experience Level and Country")
plt.xlabel("Experience Level")
plt.ylabel("Average Salary (USD)")
plt.legend(title="Country", bbox_to_anchor=(1.05,1), loc='upper left')
plt.show()

"""8 CHART: GROUPED BAR PLOT (Experience × Country)

Chart Explanation: Salary differences across countries for each experience level.

What it’s saying: Country affects salary even within the same experience.

Features used: experience_level, employee_residence, salary_in_usd

Showing us: Country-wise salary comparison.

#Pivot table
"""

pivot = df.pivot_table(values='salary_in_usd', index='job_title', columns='experience_level', aggfunc=np.mean)
pivot.head(10)

"""CHART: PIVOT TABLE (Job title x Experience level)

Explain the chart: Shows avg salary by job + experience.

What it’s saying: Different jobs pay differently at each experience level.

Features used: job_title, experience_level, salary_in_usd

Showing us: Detailed salary breakdown for each role.

#Advanced plot
"""

plt.figure(figsize=(10,6))
sizes = df['salary_in_usd'] / 150  # scale bubble size

sns.scatterplot(
    data=df,
    x='work_setting',
    y='salary_in_usd',
    hue='experience_level',
    size=sizes,
    sizes=(20,500),
    alpha=0.6
)

plt.title("Salary vs Work Setting by Experience Level (Bubble Size = Salary)")
plt.xlabel("Work Setting")
plt.ylabel("Salary (USD)")
plt.legend(bbox_to_anchor=(1.02, 1), loc='upper left')
plt.show()

""" 09 CHART: ADVANCED BUBBLE SCATTER PLOT

Chart Explanation: Salary vs work setting with bubble size indicating salary level.

What it’s saying: Salary, experience, work setting all influence together.

Features used: work_setting, salary_in_usd, experience_level

Showing us: Combined effect of salary + experience + work style.
"""

sns.jointplot(
    data=df,
    x="salary_in_usd",
    y="annual_lpa",
    kind="kde",
    fill=True,
    height=6
)

df.to_csv("jobs_in_data_2024_cleaned.csv", index=False)

print(" Cleaned dataset saved as: jobs_data_2024_cleaned.csv")

from google.colab import files
files.download("jobs_in_data_2024_cleaned.csv")

"""#STAGE 4

Documentation,Insights and Presentation
"""

print("Stage 4 documentation has been completed and the Word Document has been uploaded to Google Drive with Viewer access. Link: [https://docs.google.com/document/d/1M9-UWVjqReRo2rtfvtcoRgDvgmTHplFd/edit?usp=sharing&ouid=115078168075901931166&rtpof=true&sd=true].")

"""#FUTURE ENHANCEMENT

The analysis can be improved by using a larger and more recent dataset to capture updated market trends.

Automation of data processing and analysis can be implemented using scripts or scheduled dashboards to reduce manual effort.

More advanced and interactive visualizations can be added in Power BI to enhance user engagement and insight discovery.

The project can be extended to include predictive modeling for salary forecasting and trend analysis to support future planning.

#CONCLUSION

From the analysis, meaningful relationships and patterns were identified across salary, experience level, work setting, and company size.

The Power BI visualizations clearly highlight the key factors influencing salary outcomes, such as experience level and remote work opportunities.

Overall, the insights gained from this analysis provide a strong foundation for data-driven business decision-making and workforce planning.
"""